// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoCloseFolder
{
    internal sealed partial class Vsix
    {
        public const string Id = "1be42273-f1fb-45ad-84b8-adb55c7325aa";
        public const string Name = "Auto Close Folders";
        public const string Description = @"A Visual Studio Extension that automatically closes a folder when no document in that folder is open.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Simon Mourier";
        public const string Tags = "cleanup, collapse";
    }
}
